# Generated by Django 5.1.6 on 2025-04-27 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookmodule', '0004_student1'),
    ]

    operations = [
        migrations.CreateModel(
            name='Address2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Student2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('addresses', models.ManyToManyField(to='bookmodule.address2')),
            ],
        ),
    ]
