# Generated by Django 5.1.6 on 2025-04-27 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookmodule', '0005_address2_student2'),
    ]

    operations = [
        migrations.CreateModel(
            name='Images',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.FileField(upload_to='images/')),
                ('name', models.CharField(max_length=225)),
            ],
        ),
        migrations.AlterField(
            model_name='student2',
            name='addresses',
            field=models.ManyToManyField(related_name='addresses', to='bookmodule.address2'),
        ),
    ]
